### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by guerraleticia** [LeticiaMatosGuerra/FinalProject#1]
- palette : 

![Image](https://github.com/LeticiaMatosGuerra/FinalProject/assets/84543651/c3da29cc-b777-4fa2-9a1a-1c8db92653cc)

- Font Famili: Comfortaa

-  figma idea (mobile version) : https://www.figma.com/file/7opSsos0KRef40Cj9t8fOr/Food-Recipe-App-(Community)?type=design&node-id=1-3&t=gH52nnjAijWTQEn4-0
- figma idea desktop: https://www.figma.com/file/UtpZEbfergu7fjaYW77Ck1/Cooking-Template-%F0%9F%9F%A3-by-Flowbase.co-(Community)?type=design&node-id=1-296&t=gbyc4t2FLEoHYY4x-0

- Project_Proposal : https://docs.google.com/document/d/1hBo6Ij0Zv6QcQxiRD9sAY-WX_T0i1mSf68pBWWsuiIw/edit 

- Data Set :  

[recipes.csv](https://github.com/LeticiaMatosGuerra/FinalProject/files/11752378/recipes.csv)

**Comment by guerraleticia** [comment]
- logo : 



![Image](https://github.com/LeticiaMatosGuerra/FinalProject/assets/84543651/d925b139-8c89-423d-88f7-44715005588b)



![Image](https://github.com/LeticiaMatosGuerra/FinalProject/assets/84543651/02a87bdf-7a12-4cab-82f0-3ac6d963538e)

**Comment by Jacquesehrardt** [comment]
Figma Desktop Ideia: https://www.figma.com/file/UtpZEbfergu7fjaYW77Ck1/Cooking-Template-%F0%9F%9F%A3-by-Flowbase.co-(Community)?type=design&node-id=1-296&t=Ks3t135zIg9Wxexa-0
